### ISSUE TITLE
Double appearance of the same speaker on Badges page.

### ISSUE THREAD

**Issue by VitorPeixoto97** [cesium/intra.seium.org#103]
The badge for the speaker "Soumaya Ben Dhaou" is showing doubled in the Badges page.
![16667556_1559511414079047_1134988288_o](https://cloud.githubusercontent.com/assets/25623378/22717781/e7e39cbe-ed94-11e6-80a8-ad01c95cd7bc.png)
![16667167_1559516264078562_1397547217_o](https://cloud.githubusercontent.com/assets/25623378/22717784/f121c8b4-ed94-11e6-9230-7d8ad2f6bfee.png)

**Comment by frmendes** [comment]
@joaofcosta Don't forget about this

**Comment by 0urobor0s** [comment]
I think we can close this ...
