### ISSUE TITLE
Name of the badge is wrong

### ISSUE THREAD

**Issue by damienvaz** [cesium/intra.seium.org#64]
The image badge "Certified Detective Inspector"  (http://intra.seium.org/editions/2016/badges/75) is typed wrongly on the image.
Currently it is written "Certified Detective Inpesctor" as shown here [http://intra.seium.org/images/badges/16/random/certified_dectetive_inspector.png](url) .

P.S.: Username : Damiii

**Comment by frmendes** [comment]
@JoaoFCosta can you fix the image for this?

@damienvaz just gave you the badge.

**Comment by damienvaz** [comment]
thanks :)

**Comment by JoaoFCosta** [comment]
@frmendes Sure, i'll do it asap.
